#!/bin/sh
### BEGIN INIT INFO
# Provides:          pyredis
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Insert a description for pyredis here
### END INIT INFO

SCRIPT=pyredis

start() {
  pyredis start
}

stop() {
  pyredis stop
}

restart() {
  pyredis restart
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
